apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auctionapp
  name: auctionapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auctionapp
  template:
    metadata:
      labels:
        app: auctionapp
    spec:
      containers:
      - image: kennytoro/auctionapp
        name: auctionapp
        ports:
          - containerPort: 50

---

apiVersion: v1
kind: Service
metadata:
  name: auctionapp-svc
  labels:
    app: auctionapp
spec:
  type: NodePort
  selector:
    app: auctionapp
  ports:
    - port: 50
      targetPort: 50
      nodePort: 31007

